django_app/hello/urls.py
from django.urls import path
from . import views
from .views import FriendList
from .views import FriendDetail
urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path("edit/<int:num>", views.edit, name="edit"),
    path("delete/<int:num>", views.delete, name="delete"),
    path("list", FriendList.as_view()),
    path("detail/<int:pk>", FriendDetail.as_view()),
    path("find", views.find, name="find"),
    path("check", views.check, name="check"),  
    path("<int:num>", views.index, name="index"),  
    path("message/", views.message, name="message"),
    path("message/<int:page>", views.message, name="message"),
]

django_app/sns/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path("", views.index, name="index"),
  path("<int:page>", views.index, name="index"),
  path("post", views.post, name="post"),
  path("goods", views.goods, name="goods"),
  path("good/<int:good_id>", views.good, name="good"),
]

django_app/hello/models.py
from django.db import models
import re
from django.core.validators import ValidationError


# Create your models here.
def number_only(value):
  if (re.match(r'^[0-9]*$', value) == None):
    raise ValidationError(
      '%(value)s is not Number!',params={'value': value},
    )

class Friend(models.Model):
  name = models.CharField(max_length=100, validators=[number_only])
  mail = models.EmailField(max_length=200)
  gender = models.BooleanField()
  age = models.IntegerField()
  birthday = models.DateField()

  def __str__(self):
    return '<Friend:id=' + str(self.id) + ', ' + self.name + '(' + str(self.age) + ')>'
  

class Message(models.Model):
  friend = models.ForeignKey(Friend, on_delete=models.CASCADE)
  title = models.CharField(max_length=100)
  content = models.CharField(max_length=300)
  pub_date = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return '<Message:id=' + str(self.id) + ', ' + self.title + '(' + str(self.pub_date) + ')>'

  class Meta:
    ordering = ("pub_date",)

django_app/hello/forms.py
from django import forms
from .models import Friend, Message

class FindForm(forms.Form):
  find = forms.CharField(label="Find", required=False, widget=forms.TextInput(attrs={"class":"form-control"}))

class CheckForm(forms.Form):
  str = forms.CharField(label="String", widget=forms.TextInput(attrs={"class":"form-control"}))

  def clean(self):
    cleaned_data = super().clean()
    str = cleaned_data["str"]
    if (str.lower().startswith("no")):
      raise forms.ValidationError("You input 'NO'!")
    

class MessageForm(forms.ModelForm):
  class Meta:
    model = Message
    fields = ["title", "content", "friend"]
    widgets = {
      "title": forms.TextInput(attrs={"class":"form-conrol form-control-sm"}),
      "content": forms.Textarea(attrs={"class":"form-conrol form-control-sm", "rows":2}),
      "friend": forms.Select(attrs={"class":"form-conrol form-control-sm"}),
    }

django_app/hello/views.py
from django.shortcuts import render
from .models import Friend, Message
from django.shortcuts import redirect
from django.views.generic import ListView
from django.views.generic import DetailView
# from .forms import FindForm
from .forms import  MessageForm
from django.core.paginator import Paginator
# Create your views here.

def index(request, num=1):
  data = Friend.objects.all()
  page = Paginator(data, 3)
  params = {
    "title": "Hello",
    "message":"",
    "data": page.get_page(num),
  }
  return render(request, "hello/index.html", params)
   
def create(request):
  if (request.method == "POST"):
    obj = Friend()
    friend = FriendForm(request.POST, instance=obj)
    friend.save()
    return redirect(to="/hello")
  params = {
    "title": "Hello",
    "form": FriendForm(),
  }
  return render(request, "hello/create.html", params)

def edit(request, num):
  obj = Friend.objects.get(id=num)
  if (request.method == "POST"):
    friend = FriendForm(request.POST, instance=obj)
    friend.save()
    return redirect(to="/hello")
  params = {
    "title": "Hello",
    "id":num,
    "form": FriendForm(instance=obj),
  }
  return render(request, "hello/edit.html", params)

def delete(request, num):
  friend = Friend.objects.get(id=num)
  if (request.method == "POST"):
    friend.delete()
    return redirect(to="/hello")
  params = {
    "title": "Hello",
    "id":num,
    "obj": friend,
  }
  return render(request, "hello/delete.html", params)

class FriendList(ListView):
  model = Friend

class FriendDetail(DetailView):
  model = Friend

def find(request):
  if (request.method == 'POST'):
    msg = request.POST["find"]
    form = FindForm(request.POST)
    sql = "select * from hello_friend"
    if(msg != ""):
      sql += " where " + msg
    data = Friend.objects.raw(sql)
    msg = sql
  else:
    msg = "serch words..."
    form = FindForm()
    data = Friend.objects.all()
  params = {
    "title": "Hello",
    "message": msg,
    "form": form,
    "data":data,
  }
  return render(request, "hello/find.html", params)

def check(request):
  params = {
    "title": "Hello",
    "message": "check validation.",
    "form": CheckForm(),
  }
  if (request.method == "POST"):
    form = CheckForm(request.POST)
    params["form"] = form
    if (form.is_valid()):
      params["message"] = "OK!"
    else:
      params["message"] = "no good."
  return render(request, "hello/check.html", params)


def message(request, page=1):
  if (request.method == "POST"):
    obj = Message()
    form = MessageForm(request.POST, instance=obj)
    form.save()
  data = Message.objects.all().reverse()
  paginator = Paginator(data, 5)
  params = {
    "title": "Message",
    "form": MessageForm(),
    "data": paginator.get_page(page),
  }
  return render(request, "hello/message.html", params)

django_app/hello/templates/hello/check.html
{% load static%}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{title}}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" rel="stylesheet" crossorigin="anonymous">
</head>
<body class="container">
  <h1 class="display-4 text-primary mb-4">{{title}}</h1>
  <p>{{message|safe}}</p>
  <form action="{% url 'check' %}" method="post">
  {% csrf_token %}
    {{ form.as_table}}
        <input type="submit" value="click">
  </form>
</body>
</html>

django_app/hello/templates/hello/create.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{title}}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" rel="stylesheet" crossorigin="anonymous">
</head>
<body class="container">
  <h1 class="display-4 text-primary mb-4">{{title}}</h1>
  <form action="{% url 'create' %}" method="post">
    {% csrf_token %}
    <table class="table">
      {{ form.as_table }}
      <tr><th><td>
        <input type="submit" value="click" class="btn btn-primary mt-2">
      </td></tr></td>
    </table>
  </form>
</body>
</html>

django_app/hello/templates/hello/delete.html
{% load static%}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{title}}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" rel="stylesheet" crossorigin="anonymous">
</head>
<body class="container">
  <h1 class="display-4 text-primary mb-4">{{title}}</h1>
  <p>※以下のレコードを削除します。</p>
  <table class="table">
    <tr><th>ID</th><td>{{obj.id}}</td></tr>
    <tr><th>Name</th><td>{{obj.name}}</td></tr>
    <tr><th>Gender</th><td>
    {% if obj.gender == False %}male{% endif %}
    {% if obj.gender == True %}female{% endif %}</td></tr>
    <tr><th>Email</th><td>{{obj.mail}}</td></tr>
    <tr><th>Age</th><td>{{obj.age}}</td></tr>
    <tr><th>Birth</th><td>{{obj.birthday}}</td></tr>
    <form action="{% url 'delete' id %}" method="post">
    {% csrf_token %}
    <tr><th></th><td>
      <input type="submit" value="click" class="btn btn-primary">
    </td></tr>
    </form>
  </table>

</body>
</html>

django_app/hello/templates/hello/edit.html
{% load static%}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{title}}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" rel="stylesheet" crossorigin="anonymous">
</head>
<body class="container">
  <h1 class="display-4 text-primary mb-4">{{title}}</h1>
  <form action="{% url 'edit' id %}" method="post">
  {% csrf_token %}
    <table class="table">
    {{ form.as_table}}
      <tr><th><td>
        <input type="submit" value="click">
      </td></th></tr>
    </table>
  </form>
</body>
</html>

django_app/hello/templates/hello/find.html
{% load static%}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{title}}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" rel="stylesheet" crossorigin="anonymous">
</head>
<body class="container">
  <h1 class="display-4 text-primary mb-4">{{title}}</h1>
  <p>{{message|safe}}</p>
  <form action="{% url 'find' %}" method="post">
  {% csrf_token %}
    {{ form.as_p}}
        <input type="submit" value="click" class="btn btn-primary">
  </form>
  <hr>
  <table class="table">
    <tr>
      <th>id</th>
      <th>name</th>
      <th>age</th>
      <th>mail</th>
      <th>birthday</th>
    </tr>
    {% for item in data %}
      <tr>
        <th>{{item.id}}</th>
        <td>{{item.name}}</td>
        <td>  ({{item.age}})</td>
        <td>{{item.mail}}</td>
        <td>{{item.birthday}}</td>
      </tr>
    {% endfor %}
  </table>
</body>
</html>

django_app/hello/templates/hello/friend_detail.html
{% load static%}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{title}}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" rel="stylesheet" crossorigin="anonymous">
</head>
<body class="container">
  <h1 class="display-4 text-primary mb-4">Friend List</h1>
  <table class="table">
    <tr>
      <th>id</th><th>{{ object.id }}</th>
    </tr>
    <tr>
      <th>name</th>
      <td>{{object.name}}</td>
    <tr>
      <th>mail</th>
      <td>{{ object.mail }}</td>
    </tr>
    <tr>
      <th>gender</th>
      <td>{{ object.gender }}</td>
    </tr>
    <tr>
      <th>age</th>
      <td>{{ object.age }}</td>
    </tr>
    <tr>
      <th>birthday</th>
      <td>{{ object.birthday }}</td>
    </tr>
  </table>
</body>
</html>

django_app/hello/templates/hello/friend_list.html
{% load static%}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{title}}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" rel="stylesheet" crossorigin="anonymous">
</head>
<body class="container">
  <h1 class="display-4 text-primary mb-4">Friends List</h1>
  <table class="table">
    <tr>
      <th>id</th><th>name</th><th></th>
    </tr>
  {% for item in object_list %}
    <tr>
      <td>{{item.id}}</td>
      <td>{{item.name}}</td>
      <td><a href="/hello/detail/{{item.id}}">detail</a></td>
    </tr>
  {% endfor %}
  </table>
</body>
</html>

django_app/hello/templates/hello/index.html
{% load static%}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{title}}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" rel="stylesheet" crossorigin="anonymous">
</head>
<body class="container">
  <h1 class="display-4 text-primary">{{title}}</h1>
  <p>{{message|safe}}</p>
  <table class="table">
    <tr>
      <th>id</th><th>name</th><th>age</th><th>mail</th><th>birthday</th><th>Message</th>
    </tr>
  {% for item in data %}
    <tr>
      <td>{{item.id}}</td>
      <td>{{item.name}}</td>
      <td>{{item.age}}</td>
      <td>{{item.mail}}</td>
      <td>{{item.birthday}}</td>
      <td>
        <ul>
          {% for ob in item.message_set.all %}
            <li>{{ob.title}}</li>
          {% endfor %}
        </ul>
      </td>
    </tr>
  {% endfor %}
  </table>
  <ul class="pagination justify-content-center">
    {% if data.has_previous %}
    <li class="page-item">
      <a class="page-link" href="{% url 'index' %}">&laquo; first</a>
    </li>
    <li class="page-item">
      <a href="{% url 'index' %}{{data.previous_page_number}}" class="page-link">
        &laquo; prev
      </a>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link">&laquo; first</a>
    </li>
    <li class="page-item">
      <a class="page-link">&laquo; prev</a>
    </li>
    {% endif %}
    <li class="page-item">
      <a class="page-link">{{data.number}}/{{data.paginator.num_pages}}</a>
    </li>
    {% if data.has_next %}
    <li class="page-item">
      <a href="{% url 'index' %}{{data.next_page_number}}" class="page-link">
        next &laquo;
      </a>
    </li>
    <li class="page-item">
      <a href="{% url 'index' %}{{data.paginator.num_pages}}" class="page-link">
        last &laquo;
      </a>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link">next &laquo;</a>
    </li>
        <li class="page-item">
      <a class="page-link">last &laquo;</a>
    </li>
    {% endif %}
  </ul>
</body>
</html>

django_app/hello/templates/hello/message.html
{% load static%}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{title}}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css" rel="stylesheet" crossorigin="anonymous">
</head>
<body class="container">
  <h1 class="display-4 text-primary">{{title}}</h1>
    <form action="{% url 'message' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
      <input type="submit" value="send" class="btn btn-primary">
    </form>
  <div class="mt-5">
    <table class="table">
      <tr>
        <th class="py-1">title</th><th class="py-1">name</th><th class="py-1">datetime</th>
      </tr>
    {% for item in data %}
      <tr>
        <th class="py-2">{{item.title}}</th><th class="py-2">{{item.friend.name}}</th><th class="py-2">{{item.pub_date}}</th>
      </tr>
    {% endfor %}
    </table>
  </div>
  <ul class="pagination justify-content-center">
    {% if data.has_previous %}
    <li class="page-item">
      <a class="page-link" href="{% url 'message' %}">&laquo; first</a>
    </li>
    <li class="page-item">
      <a href="{% url 'message' %}{{data.previous_page_number}}" class="page-link">
        &laquo; prev
      </a>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link">&laquo; first</a>
    </li>
    <li class="page-item">
      <a class="page-link">&laquo; prev</a>
    </li>
    {% endif %}
    <li class="page-item">
      <a class="page-link">{{data.number}}/{{data.paginator.num_pages}}</a>
    </li>
    {% if data.has_next %}
    <li class="page-item">
      <a href="{% url 'message' %}{{data.next_page_number}}" class="page-link">
        next &laquo;
      </a>
    </li>
    <li class="page-item">
      <a href="{% url 'message' %}{{data.paginator.num_pages}}" class="page-link">
        last &laquo;
      </a>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link">next &laquo;</a>
    </li>
        <li class="page-item">
      <a class="page-link">last &laquo;</a>
    </li>
    {% endif %}
  </ul>
</body>
</html>